apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-fortune
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: fortune
  template:
    metadata:
      labels:
        app: fortune
    spec:
      containers:
        - name: fortune
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000