replicaCount: 1

image:
  # harbor
  # repository: 172.16.8.40/library/fortune
  # ecr
  repository: 336925002301.dkr.ecr.ap-northeast-2.amazonaws.com/fortune
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000 # FastAPI 포트